### ISSUE TITLE
Sound doesn't output on Mega 2560 board

### ISSUE THREAD

**Issue by ghost** [blakelivingston/DuinoTune#5] opened 2017-01-08 17:02 UTC
It actually doesn't even compile, due to the defines missing definitions for the board. After working around that, it compiles, but doesn't output any sound. It does still work just find on my Uno board.

**Comment by egyware** [comment] 2017-01-30 22:08
I don't know how works all that registers and timers. But I the problem is board, it works too diferent.

Maybe you have more luck trying this http://forum.arduino.cc/index.php?topic=103617.0

PS: Also I have Mega2560 too, and doesn't work
PS: I changed DDRD |= (1 << PD3) by DDRH = 0xff, but sound... well it's works!!

**Comment by ghost** [comment] 2017-02-04 09:17
I'll have to try that out! Right now I have the Mega hooked up to the Uno via jumper cables in true hacking fashion. It's actually kind of nice to have a separate program controlling sound.

**Comment by blakelivingston** [comment] 2017-02-16 20:56
Hi all. Thanks for the feedback and interest in the project!
 I'm going through and adding support for some new MCUs (Leonardo works now). I've added experimental support for Mega 2560. It builds for me at least, but if someone would like test it I'd be much obliged. It should output on Arduino pin 4, or PG5 on the MCU.

**Comment by ghost** [comment] 2017-03-29 14:13
Sorry for the quite late reply. I've tried it out. Unfortunately, the sound output isn't correct. It plays the first note, then just plays what sounds kind of like corrupted data or something. So not quite working yet.

**Comment by blakelivingston** [comment] 2017-03-29 18:23
Cool! If it's making sound then that's better than I'd have hoped for not having the hardware to test the build!
Just checked and the default sample rate for the mega2560 is pretty aggressive at 22khz. If you could edit src/tinytune/settings.h and reduce it to something like 12000L that may make it work.
You can adjust up the sample rate to whatever works for the song you're playing.

#if defined (__ATmega2560__)
#define N_VOICES 11
#define SAMPLE_BUFFER 64
#define SAMPLE_RATE 22000UL  -> 12000L

Let me know if it works and I'll update the default.

**Comment by ghost** [comment] 2017-03-30 15:18
That worked! It now sounds essentially identical to what it sounds like on my Uno board.

**Comment by blakelivingston** [comment] 2017-05-30 01:48
Closing (fixed)

**Closed as completed by blakelivingston** 2017-05-30 01:48 UTC
